# Generated by Django 4.1.3 on 2022-11-24 16:40

from django.db import migrations, models

ADD_VALUES = '''
INSERT INTO tasks_place (id, description) VALUES (0, 'En cualquier
lugar');
INSERT INTO tasks_place (id, description) VALUES (1, 'En la calle');
INSERT INTO tasks_place (id, description) VALUES (2, 'En casa');
INSERT INTO tasks_place (id, description) VALUES (3, 'En la
oficina');'''
''

REMOVE_VALUES = '''
DELETE FROM tasks_place WHERE id IN (0, 1, 2, 3);
'''



class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_project_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(ADD_VALUES, REMOVE_VALUES),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Lugar",
                "verbose_name_plural": "Lugares",
            },
        ),
    ]
