# Generated by Django 4.1.3 on 2022-11-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="place",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.place",
            ),
        ),
    ]
